cmd_drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o := /home/mylinux/rk3288/myrk3128/kernel/scripts/gcc-wrapper.py ../prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi-gcc -Wp,-MD,drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/.esp_slab.o.d  -nostdinc -isystem /home/mylinux/rk3288/myrk3128/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/../lib/gcc/arm-eabi/4.6.x-google/include -I/home/mylinux/rk3288/myrk3128/kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/mylinux/rk3288/myrk3128/kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/mylinux/rk3288/myrk3128/kernel/include/uapi -Iinclude/generated/uapi -include /home/mylinux/rk3288/myrk3128/kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DESP_PRE_MEM    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(esp_slab)"  -D"KBUILD_MODNAME=KBUILD_STR(esp_prealloc)" -c -o drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.c

source_drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o := drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.c

deps_drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o := \

drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o: $(deps_drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o)

$(deps_drivers/net/wireless/rockchip_wlan/esp8089/esp_premalloc/esp_slab.o):
